routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});
Route::group(['prefix'=>'admin','middleware'=>'adminLogin'],function()
{
    Route::resource('categories','CategoryController');
	Route::resource('articles','ArticleController');
	Route::get('/articles/category/{id}','CategoryController@showArticle');
});

Route::get('admin/register','AccountController@getRegisterAdmin');
Route::post('admin/register','AccountController@postRegisterAdmin');
Route::get('admin/login','AccountController@getLoginAdmin');
Route::post('admin/login','AccountController@postLoginAdmin');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $table = 'category_articles';
    protected $fillable = ['id', 'name'];

    public function article()
    {
        return $this->hasMany('App\Article', 'category_id', 'id');
    }

    public function showCategoryArticle()
    {
        $categorys = Category::paginate(5);
        return $categorys;
    }

    public function addCategoryArticle($input)
    {
        $category = new Category();
        $category->id = $input->id;
        $category->name = $input->name;
        $category->save();
        return $category;
    }

    public function updateCategoryArticle($input, $id)
    {
        $category = Category::findOrFail($id);
        $category->name = $input->name;
        $category->save();

        return $category;
    }

    public function deleteCategoryArticle($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();

        return $category;
    }

    public function searchCategoryArticle($key)
    {
        $categorys = Category::where('category_articles.name', 'like', "%$key%")
            ->paginate(5);
        return $categorys;
    }

    public function showListArticle($id)
    {
        $articles = Article::select('articles.*')
            ->join('category_articles', 'articles.category_id', '=', 'category_articles.id')
            ->where('articles.category_id', '=', $id)
            ->get();
        return $articles;
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\CategoryRequest;
use Illuminate\Http\Request;
use Validator;

class CategoryController extends Controller
{

    function __construct(Category $category)
    {
        $this->category = $category;
    }

    public function index(Request $request)
    {
        $categories = $this->category->showCategoryArticle();
        return view('admin.category.list', compact('categories'));
    }


    public function store(CategoryRequest $request)
    {
        $category = $this->category->addCategoryArticle($request);
        return response()->json($category);
    }

    public function update(CategoryRequest $request, $id)
    {
        $category = $this->category->updateCategoryArticle($request, $id);
        return response()->json($category);
    }

    public function destroy($id)
    {
        $category = $this->category->deleteCategoryArticle($id);

        return response()->json($category);
    }

    public function show(Request $request)
    {
        $key = $request->keyword;
        $categories = $this->category->searchCategoryArticle($key);
        return view('admin.category.search', ['categories' => $categories, 'key' => $key]);
    }

    public function showArticle($id)
    {
        $categories = Category::all();
        $articles = $this->category->showListArticle($id);
        return view('admin.category.show', ['articles' => $articles, 'categories' => $categories]);
    }
}

resources/views/admin/category/add.blade.php
<!-- Modal form to add a category -->
<div id="addModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" style="color: green ">Create a new category article</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="name">Name:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="name_add" autofocus>
                            <small>Min: 2, Max: 128, only text</small>
                        </div>
                    </div>

                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success add" data-dismiss="modal">
                        <span id="" class='glyphicon glyphicon-check'></span> Add
                    </button>
                    <button type="button" class="btn btn-warning" data-dismiss="modal">
                        <span class='glyphicon glyphicon-remove'></span> Close
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/admin/category/delete.blade.php
<!-- Modal form to delete a form -->
<div id="deleteModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" style="color: red">Delete a category article</h4>
            </div>
            <div class="modal-body">
                <h3 class="text-center">Are you want to delete the following category?</h3>
                <br/>
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="id">ID:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="id_delete" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="name">Name:</label>
                        <div class="col-sm-10">
                            <input type="name" class="form-control" id="name_delete" disabled>
                        </div>
                    </div>
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger delete" data-dismiss="modal">
                        <span id="" class='glyphicon glyphicon-trash'></span> Delete
                    </button>
                    <button type="button" class="btn btn-warning" data-dismiss="modal">
                        <span class='glyphicon glyphicon-remove'></span> Close
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/admin/category/edit.blade.php
<!-- Modal form to edit a form -->
<div id="editModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" style="color: green">Update a category article</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="id">ID:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="id_edit" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="name">Name:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="name_edit" autofocus>
                            <small>Min: 2, Max: 128, only text</small>
                            <p class="errorName text-center alert alert-danger hidden"></p>
                        </div>
                    </div>
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary edit" data-dismiss="modal">
                        <span class='glyphicon glyphicon-check'></span> Edit
                    </button>
                    <button type="button" class="btn btn-warning" data-dismiss="modal">
                        <span class='glyphicon glyphicon-remove'></span> Close
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/admin/category/list.blade.php
@extends('admin.layout.index')
@section('content')
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">

                <div class="card">
                    <div class="card-action">
                        Category Tables <br>
                        <button class="add-modal btn btn-success" data-target="#addModal" data-toggle="modal"
                                style="float:right">
                            <span class="glyphicon glyphicon-eye-open"></span>Add category
                        </button>
                        <form action="admin/categories/search" method="" class="navbar-form navbar-left"
                              role="search">
                            <div class="form-group">
                                <input type="text" name="keyword" class="form-control" placeholder="Search">
                            </div>
                            <button type="submit" class="btn btn-default"
                                    style="background-color: #3399FF; color: white;">Tìm kiếm
                            </button>
                        </form>
                    </div>
                    <br><br>
                    <div class="card-content">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($categories as $c_infor)
                                    <tr class="odd gradeX" id="indexcategory{{$c_infor->id}}">
                                        <td>{{$c_infor->id}}</td>
                                        <td><a href="/admin/articles/category/{{$c_infor->id}}">{{$c_infor->name}}</a>
                                        </td>
                                        <td>
                                            <button class="edit-modal center btn btn-info" data-id="{{$c_infor->id}}"
                                                    data-name="{{$c_infor->name}}" data-target="#editModal"
                                                    data-toggle="modal">
                                                <span class="glyphicon glyphicon-edit"></span> Edit
                                            </button>
                                            <button class="delete-modal center btn btn-danger"
                                                    data-id="{{$c_infor->id}}" data-name="{{$c_infor->name}}"
                                                    data-target="#deleteModal" data-toggle="modal">
                                                <span class="glyphicon glyphicon-trash"></span> Delete
                                            </button>

                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            {{ $categories->links() }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
     <!--End Advanced Tables -->

    @include('admin.category.add')
    @include('admin.category.edit')
    @include('admin.category.delete')
    @include('admin.category.html')

    <!--AJAX CRUD-->
    <script type="text/javascript" src="js/ajaxcategory.js"></script>

@endsection

resources/views/admin/category/search.blade.php
@extends('admin.layout.index')
@section('content')
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">

                <div class="card">
                    <div class="card-action">
                        Category Tables Search: {{$key}}<br>
                        <a href="/admin/categories">
                            <button class="add-modal btn btn-success"
                                    style="float:right">
                                <span class="glyphicon glyphicon-eye-open"></span>Back to category
                            </button>
                        </a>
                        <button class="add-modal btn btn-success" data-target="#addModal" data-toggle="modal"
                                style="float:right">
                            <span class="glyphicon glyphicon-eye-open"></span>Add category
                        </button>
                        <form action="/admin/categories/search" method="" class="navbar-form navbar-left"
                              role="search">

                            <div class="form-group">
                                <input type="text" name="keyword" class="form-control" placeholder="Search">
                            </div>
                            <button type="submit" class="btn btn-default"
                                    style="background-color: #3399FF; color: white;">Tìm kiếm
                            </button>
                        </form>
                    </div>
                    <br><br>
                    <?php
                    function changeColor($str, $key)
                    {
                        $result = str_replace($key, "<span style = 'color:red;'>$key</span>", $str);
                        return $result;
                    }
                    ?>
                    <div class="card-content">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($categories as $c_infor)
                                    <tr class="odd gradeX" id="indexcategory{{$c_infor->id}}">
                                        <td>{{$c_infor->id}}</td>
                                        <td>
                                            <a href="admin/article/category/{{$c_infor->id}}">{!! changeColor($c_infor->name , $key)!!}</a>
                                        </td>
                                        <td>
                                            <button class="edit-modal center btn btn-info" data-id="{{$c_infor->id}}"
                                                    data-name="{{$c_infor->name}}" data-target="#editModal"
                                                    data-toggle="modal">
                                                <span class="glyphicon glyphicon-edit"></span> Edit
                                            </button>
                                            <button class="delete-modal center btn btn-danger"
                                                    data-id="{{$c_infor->id}}" data-name="{{$c_infor->name}}"
                                                    data-target="#deleteModal" data-toggle="modal">
                                                <span class="glyphicon glyphicon-trash"></span> Delete
                                            </button>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            {{ $categories->appends(['keyword' => $key])->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--End Advanced Tables -->

    @include('admin.category.add')
    @include('admin.category.edit')
    @include('admin.category.delete')

    <!--AJAX CRUD-->
    <script type="text/javascript" src="js/ajaxcategory.js"></script>

@endsection

resources/views/admin/category/show.blade.php
@extends('admin.layout.index')
@section('content')
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-action">
                            Article Tables<br>
                            <a href="/admin/category">
                                <button class=" btn btn-success" style="float:right">
                                    <span class="glyphicon"></span>Back to Category
                                </button>
                            </a>
                            <button class="add-modal btn btn-success" data-target="#addModal" data-toggle="modal"
                                    style="float:right">
                                <span class="glyphicon glyphicon-eye-open"></span>Add article
                            </button>
                            <form action="{{ route('articles.index') }}" method="" class="navbar-form navbar-left"
                                  role="search">

                                <div class="form-group">
                                    <input type="text" name="search" class="form-control" placeholder="Search">
                                </div>
                                <button type="submit" class="btn btn-default"
                                        style="background-color: #3399FF; color: white;">Tìm kiếm
                                </button>
                            </form>
                        </div>
                        <br><br>
                        <div class="card-content">
                            <div class="table-responsive">

                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Category</th>
                                        <th>Title</th>
                                        <th>Content</th>
                                        <th>Address</th>
                                        <th>Status</th>
                                        <th>Phone Number</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($articles as $a_infor)
                                        <tr class="odd gradeX" id="indexArticle{{$a_infor->id}}">
                                            <td>{{$a_infor->id}}</td>
                                            <td>{{$a_infor->categoryarticle['name']}}</td>
                                            <td>{{$a_infor->title}}</td>
                                            <td>{{$a_infor->content}}</td>
                                            <td>{{$a_infor->address}}</td>
                                            <td>{{$a_infor->status}}</td>
                                            <td>{{$a_infor->phonenumber}}</td>
                                            <td>
                                                <button class="center btn btn-info edit-modal"
                                                        data-id="{{$a_infor->id}}"
                                                        data-category="{{$a_infor->category_id}}"
                                                        data-title="{{$a_infor->title}}"
                                                        data-content="{{$a_infor->content}}"
                                                        data-address="{{$a_infor->address}}"
                                                        data-phonenumber="{{$a_infor->phonenumber}}"
                                                        data-status="{{$a_infor->status}}" data-target="#editModal"
                                                        data-toggle="modal">
                                                    <span class="glyphicon glyphicon-edit"></span>Edit
                                                </button>
                                                <button class="delete-modal center btn btn-danger"
                                                        data-id="{{$a_infor->id}}"
                                                        data-category="{{$a_infor->category_id}}"
                                                        data-title="{{$a_infor->title}}"
                                                        data-content="{{$a_infor->content}}"
                                                        data-address="{{$a_infor->address}}"
                                                        data-phonenumber="{{$a_infor->phonenumber}}"
                                                        data-status="{{$a_infor->status}}" data-target="#deleteModal"
                                                        data-toggle="modal">
                                                    <span class="glyphicon glyphicon-trash"></span>Delete
                                                </button>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('admin.article.add')
    @include('admin.article.edit')
    @include('admin.article.delete')


    <!--AJAX CRUD-->
    <script type="text/javascript" src="js/ajaxarticle.js"></script>
@endsection